### ISSUE TITLE
[Config] AWS 인프라 개발 환경 구축

### ISSUE THREAD

**Issue by jola7373** [DeveloperAcademy-POSTECH/MacC-Team-EarthValley80-Server#6]
## 💡 무엇을/어떻게/왜 설정하나요? 

전반적인 인프라 환경 구축 및 설계 필요!

## 📝  todo
- [ ] 프로젝트 전반 인프라 환경 설계
- [ ] 배포 설정
- [ ] 배포 자동화 설정
- [ ] 무중단 배포 설정
- [ ] DB 생성
