### ISSUE TITLE
[Bugfix] secretkey 환경변수로 관리

### ISSUE THREAD

**Issue by jola7373** [DeveloperAcademy-POSTECH/MacC-Team-EarthValley80-Server#65]
## 💡 Error의 원인과 내용은 무엇인가요? 

jwt 환경 설정 파일을 gitignore처리 하였을때 CI 과정중 gradlew clean build시 Test case에서 필요한 환경이 없어 발생하는 문제

## 해결 방법
환경설정 관련내용은 깃에 같이 올리지만 노출 되서는 안되는 정보는 환경변수 파일을 따로 만들어 관리한다.
해당 환경변수 파일은 gitignore 처리하고 CI과정에서 빌드전에 환경변수파일을 생성하는 과정을 거친다. (이때 노출되서 안되는 정보는 github secrets로 관리 한다.

## 📝  todo
- [ ] env 파일 로컬에서 따로 분리 후 빌드 확인
- [ ] github secret 키 생성
- [ ] 이 후 github action script에 env 파일 생성 스크립트 작성
