### ISSUE TITLE
[Feat] Article Entity 정의 

### ISSUE THREAD

**Issue by jola7373** [DeveloperAcademy-POSTECH/MacC-Team-EarthValley80-Server#85]
## 💡 어떤 기능을 구현하나요? 

Article Entity를 정의한다.

처음에 DynamoDB를 사용하려 했으나 생각보다 높은 Learning curve와 시간부족으로 우선 RDB를 사용하기로 결정했다.

### Future Plan
추후에 DynamoDB나 MongoDB로 이전 예정이다.

## 📝  todo
- [ ] Article Entity layer 코드 작성
- [ ] Section Entity layer 코드 작성
- [ ] Info Entity layer 코드 작성
- [ ] DB 연동 Test 진행
