### ISSUE TITLE
[Feat] Article 하나 불러오기

### ISSUE THREAD

**Issue by jola7373** [DeveloperAcademy-POSTECH/MacC-Team-EarthValley80-Server#92]
## 💡 어떤 기능을 구현하나요? 

- get one article detail

## 📝  todo
- [x] 기사 detail 불러오기 repository
- [x] 기사 detail 불러오기 service
- [x] 기사 detail 불러오기 controller
