### ISSUE TITLE
[Feat] 뉴스 읽기 기록 생성

### ISSUE THREAD

**Issue by jola7373** [DeveloperAcademy-POSTECH/MacC-Team-EarthValley80-Server#96]
## 💡 어떤 기능을 구현하나요? 

- 뉴스 읽기 기록을 생성 하는 api

## 📝  todo
- [ ] 뉴스 읽기 기록을 생성 controller
- [ ] 뉴스 읽기 기록 생성 service
- [ ] 뉴스 읽기 기록 생성 repository
